#!/bin/bash

HAS_ISSUES=0

for file in $(git diff --name-only --staged); do
    FMT_RESULT="$(rustfmt --check diff $file 2>/dev/null || true)"
    if [ "$FMT_RESULT" != "" ]; then
        echo "$file,"
        HAS_ISSUES=1
    fi
done

if [ $HAS_ISSUES -eq 0 ]; then
    exit 0
fi

echo
echo "The files listed above has formatting errors. Format your code before commiting."
exit 1
